### ISSUE TITLE
Error on installing from pip

### ISSUE THREAD

**Issue by ArbitRandomUser** [rocky/FoxySheep2#5]
i get this error on  running the binary 
```
Traceback (most recent call last):
  File "/home/antineutrino/.local/bin/foxy-sheep", line 5, in <module>
    from FoxySheep.__main__ import main
  File "/home/antineutrino/.local/lib/python3.7/site-packages/FoxySheep/__init__.py", line 13, in <module>
    from FoxySheep.emitter.full_form import FullFormEmitter, input_form_to_full_form
ModuleNotFoundError: No module named 'FoxySheep.emitter'
```

**Comment by rocky** [comment]
In short this is a bit too vague for me to know if there is a bug or more likely a mistake on your part or misunderstanding in how things are supposed to work. 

rms gave a some advice long long time ago that is wish many people would get into the habit of when reporting a problem. 

*I can't find where but it was probably in an old Emacs manual),

He said that you should give not just an error message you encountered e.g. "Command not found", but also the input or command you ran leading up to that input. 

It is easier to ignore information that isn't need than to fill in or guess what crucial piece of information is missing. 

That said, from what is shown above, I would imagine you are not familiar with Python and how to install python packages. 

Here is an example of what I tried and what worked for me

```
$ pyenv local 3.8.13
$ pip install -e .
Obtaining file:///tmp/rocky/FoxySheep2
  Preparing metadata (setup.py) ... done
Collecting antlr4-python3-runtime<4.8,>=4.7
  Downloading antlr4-python3-runtime-4.7.2.tar.gz (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 KB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: click>=7.1.2 in /home/rocky/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from FoxySheep==1.2.3) (8.0.4)
Collecting astor
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: PyYAML in /home/rocky/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from FoxySheep==1.2.3) (6.0)
Collecting astpretty
  Using cached astpretty-2.1.0-py2.py3-none-any.whl (5.3 kB)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.7.2-py3-none-any.whl size=140950 sha256=8fb30691f9336b8a982a5a9ac2a376322487c8b2f5dc88488a0370ede6f2d6a5
  Stored in directory: /home/rocky/.cache/pip/wheels/63/93/52/480c17789fbf685f5d0e33e83c311f4a844cd6e2f5cf036c03
Successfully built antlr4-python3-runtime
Installing collected packages: antlr4-python3-runtime, astpretty, astor, FoxySheep
  Running setup.py develop for FoxySheep
Successfully installed FoxySheep-1.2.3 antlr4-python3-runtime-4.7.2 astor-0.8.1 astpretty-2.1.0
$ foxy-sheep --help
Usage: foxy-sheep [OPTIONS]

Options:
  --repl / --no-repl              Go into REPL
  -t, --tree [full|compact]       show parse tree(s) created
  -i, --input-style [inputform|fullform]
  -o, --output-style [python|sympy|numpy|scipy|fullform]
  -d, --debug                     Show extra debugging information
  -s, --session / --no-session    In REPL, evaluate the translation and in
                                  REPL session
  -f, --file PATH                 file of Mathematica expressions
  -e, --expr TEXT                 translate *expr*
  --version                       Show the version and exit.
  --help                          Show this message and exit.
```

See if you can come up with something comparable.

**Comment by ArbitRandomUser** [comment]
i'm sorry , yes i should have been more clear with my problem.
i was running
`pip install foxysheep`
and then running 
`foxysheep` on a new terminal.  Which was causing the errors that i had mentioned earlier.

What you prescribed in your comment worked, thanks
